# Generated by Django 5.2.14 on 2026-05-29 16:34

import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('identity', '0002_otpcode'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('photo', 'Photograph (meter or property)'), ('csv', 'Spreadsheet of readings (CSV)'), ('statement_pdf', 'Municipal statement (PDF)')], max_length=16)),
                ('file', models.FileField(upload_to=portal.models.evidence_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=80)),
                ('size_bytes', models.PositiveIntegerField()),
                ('municipal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='ingest.municipalaccount')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
                ('ratepayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_uploaded', to='identity.ratepayer')),
            ],
            options={
                'indexes': [models.Index(fields=['municipality', 'ratepayer', '-created_at'], name='portal_evid_municip_dd6ca9_idx'), models.Index(fields=['municipality', 'municipal_account', '-created_at'], name='portal_evid_municip_2659c8_idx')],
            },
        ),
    ]
