# Generated by Django 5.2.14 on 2026-05-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlmExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('low_confidence', 'Low confidence (review)'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('reading_kl', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, help_text='Provider model identifier — e.g. claude-sonnet-4-6.', max_length=64)),
                ('raw_response', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vlm_extraction', to='portal.evidence')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
            ],
            options={
                'indexes': [models.Index(fields=['municipality', 'status', '-created_at'], name='vlm_vlmextr_municip_10ff82_idx')],
            },
        ),
    ]
