# Generated by Django 5.2.14 on 2026-05-29 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(help_text='First day of the billing month.')),
                ('kind', models.CharField(choices=[('opening', 'Opening balance brought forward'), ('charge_accepted', 'Charge accepted as billed'), ('charge_corrected', 'Charge corrected (engine adjustment)'), ('payment_received', 'Payment received')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed. Positive = ratepayer owes more; negative = correction or payment.', max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('municipal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='ingest.municipalaccount')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
            ],
            options={
                'indexes': [models.Index(fields=['municipality', 'municipal_account', 'period'], name='ledger_ledg_municip_02037d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReconciledPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField()),
                ('municipality_balance', models.DecimalField(decimal_places=2, help_text='The closing balance from MunicipalBill at recompute time.', max_digits=12)),
                ('our_balance', models.DecimalField(decimal_places=2, help_text='What we say the ratepayer owes after applying findings.', max_digits=12)),
                ('delta', models.DecimalField(decimal_places=2, help_text='our_balance - municipality_balance. Signed.', max_digits=12)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('municipal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciled_positions', to='ingest.municipalaccount')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
            ],
            options={
                'indexes': [models.Index(fields=['municipality', 'period'], name='ledger_reco_municip_755601_idx')],
                'constraints': [models.UniqueConstraint(fields=('municipal_account', 'period'), name='ledger_reconciledposition_unique_per_period')],
            },
        ),
    ]
