# Generated by Django 5.2.14 on 2026-05-29 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratepayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('msisdn', models.CharField(blank=True, help_text='E.164 phone number, e.g. +27821234567. Nullable until learned.', max_length=20, null=True)),
                ('id_last4', models.CharField(blank=True, help_text='Last 4 digits of ID. Fallback identifier for ratepayers with no mobile on file.', max_length=4, null=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='RatepayerAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratepayer_links', to='ingest.municipalaccount')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
                ('ratepayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='identity.ratepayer')),
            ],
        ),
        migrations.AddIndex(
            model_name='ratepayer',
            index=models.Index(fields=['municipality', 'msisdn'], name='identity_ra_municip_baddb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratepayer',
            constraint=models.UniqueConstraint(condition=models.Q(('msisdn__isnull', False)), fields=('municipality', 'msisdn'), name='identity_ratepayer_unique_msisdn_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='ratepayeraccountlink',
            index=models.Index(fields=['municipality', 'municipal_account'], name='identity_ra_municip_c84a58_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratepayeraccountlink',
            constraint=models.UniqueConstraint(fields=('ratepayer', 'municipal_account'), name='identity_link_unique_per_ratepayer_account'),
        ),
    ]
