# Generated by Django 5.2.14 on 2026-05-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=8)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
                ('ratepayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='identity.ratepayer')),
            ],
            options={
                'indexes': [models.Index(fields=['municipality', 'ratepayer', '-created_at'], name='identity_ot_municip_cfa43f_idx')],
            },
        ),
    ]
