# Generated by Django 5.2.14 on 2026-05-29 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField()),
                ('content_hash', models.CharField(max_length=64)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('received', 'received'), ('imported', 'imported'), ('failed', 'failed')], default='received', max_length=16)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(max_length=32)),
                ('holder_name', models.CharField(max_length=200)),
                ('service_address', models.TextField()),
                ('account_class', models.CharField(max_length=64)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
                ('source_extract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='ingest.extract')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_date', models.DateField()),
                ('reading_kl', models.PositiveIntegerField()),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
                ('source_extract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='ingest.extract')),
                ('municipal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='ingest.municipalaccount')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(help_text='First day of the billing month (day=1).')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charges', models.JSONField(default=dict)),
                ('payments', models.JSONField(default=dict)),
                ('municipal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='ingest.municipalaccount')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
                ('source_extract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='ingest.extract')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField()),
                ('kind', models.CharField(choices=[('charge', 'charge'), ('payment', 'payment'), ('journal', 'journal')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('raw_row', models.JSONField(default=dict)),
                ('municipal_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ingest.municipalbill')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
                ('source_extract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='ingest.extract')),
            ],
        ),
        migrations.AddIndex(
            model_name='extract',
            index=models.Index(fields=['municipality', 'received_at'], name='ingest_extr_municip_9eea74_idx'),
        ),
        migrations.AddConstraint(
            model_name='extract',
            constraint=models.UniqueConstraint(fields=('municipality', 'content_hash'), name='ingest_extract_unique_content_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='municipalaccount',
            index=models.Index(fields=['municipality', 'account_number'], name='ingest_muni_municip_5a08fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='municipalaccount',
            constraint=models.UniqueConstraint(fields=('municipality', 'account_number'), name='ingest_municipalaccount_unique_account_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['municipality', 'reading_date'], name='ingest_mete_municip_22c9dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(fields=('municipal_account', 'reading_date'), name='ingest_meterreading_unique_date_per_account'),
        ),
        migrations.AddIndex(
            model_name='municipalbill',
            index=models.Index(fields=['municipality', 'period'], name='ingest_muni_municip_d37dec_idx'),
        ),
        migrations.AddConstraint(
            model_name='municipalbill',
            constraint=models.UniqueConstraint(fields=('municipal_account', 'period'), name='ingest_municipalbill_unique_period_per_account'),
        ),
        migrations.AddIndex(
            model_name='municipalledgerentry',
            index=models.Index(fields=['municipality', 'entry_date'], name='ingest_muni_municip_79eed5_idx'),
        ),
    ]
