"""
Django settings for primeserve project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kxq&my_ojlxsa#vf_2j(pw4@4_^_0xca^0+_rifqsb!42#7$tq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_rq',
    'common',
    'identity',
    'ingest',
    'engine',
    'vlm',
    'ledger',
    'payments',
    'corrections',
    'portal',
    'channels.whatsapp',
    'channels.ussd',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'primeserve.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'primeserve.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'primeserve_dev',
        'USER': 'primeserve',
        'PASSWORD': 'primeserve_dev_only',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# RQ (background tasks)
# https://github.com/rq/django-rq

# ASYNC=False executes jobs inline. Keyed to `python manage.py test` — if
# the project ever moves to pytest, replace this toggle with a dedicated
# test-settings module.
_IS_TEST_RUN = 'test' in sys.argv

RQ_QUEUES = {
    'default': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': 360,
        'ASYNC': not _IS_TEST_RUN,
    },
}


# Ingest

INGEST_INBOX_DIR = BASE_DIR / 'dev_inbox'


# Tenancy
# MVP is Emfuleni-only; common.services.get_current_tenant() returns the
# Municipality with this slug regardless of the request. Q7 swaps this for
# subdomain or path-prefix resolution when a second tenant lands.

DEFAULT_TENANT_SLUG = 'emfuleni'


# Portal
# Session key the portal uses to track the logged-in ratepayer.

PORTAL_SESSION_KEY = 'portal:ratepayer_id'


# Media — ratepayer-uploaded evidence (Slice 5)
# Layout: MEDIA_ROOT/<tenant_slug>/evidence/<uuid>.<ext>. Swap to S3 in
# af-south-1 (Q8) is a config-only change via DEFAULT_FILE_STORAGE.

MEDIA_ROOT = BASE_DIR / 'dev_media'
MEDIA_URL = '/media/'


# Per-evidence-kind validation. Sizes are bytes; allowed_exts is the
# whitelist of file extensions (lowercase, no dot). Tightening these is
# easier than loosening them later — start conservative.

EVIDENCE_MAX_BYTES = 10 * 1024 * 1024  # 10 MiB

EVIDENCE_KIND_RULES = {
    'photo': {
        'allowed_exts': ('jpg', 'jpeg', 'png', 'heic', 'webp'),
        'allowed_mimes': ('image/jpeg', 'image/png', 'image/heic', 'image/webp'),
    },
    'csv': {
        'allowed_exts': ('csv',),
        'allowed_mimes': ('text/csv', 'application/vnd.ms-excel', 'text/plain'),
    },
    'statement_pdf': {
        'allowed_exts': ('pdf',),
        'allowed_mimes': ('application/pdf',),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
