# Generated by Django 5.2.14 on 2026-05-29 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('ingest', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(help_text='First day of the billing month (day=1).')),
                ('archetype', models.CharField(choices=[('estimate_cap_breach', 'Estimate cap breach (MSA s95)'), ('tariff_misapplied', 'Tariff misapplied'), ('meter_reading_disputed', 'Meter reading disputed')], max_length=64)),
                ('delta_amount', models.DecimalField(decimal_places=2, help_text='Signed. Negative = municipality appears to have overcharged.', max_digits=12)),
                ('statutory_ref', models.CharField(blank=True, help_text="e.g. 'MSA s95' for estimate-cap findings.", max_length=64)),
                ('explanation', models.TextField(blank=True, help_text='Plain-English explanation safe to show the ratepayer.')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='portal.evidence')),
                ('municipal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='ingest.municipalaccount')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='common.municipality')),
            ],
            options={
                'indexes': [models.Index(fields=['municipality', 'municipal_account', 'period'], name='engine_find_municip_4561d4_idx')],
            },
        ),
    ]
